# Sample workflow for building and deploying a Action-EJS site to GitHub Pages
name: Deploy action-ejs with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generateInputPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix with all modules of WhatTheHack repository
        id: set-matrix
        run: |
          mkdir _site
          ls -l
          echo "index=$(find . -maxdepth 1 -name '*.md' -type f -print | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
          echo "schemas=$(find ./_schemas -maxdepth 1 -name '*.md' -type f -print | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
          echo "contexts=$(find ./_contexts -maxdepth 1 -name '*.md' -type f -print | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
    outputs:
      schemas: ${{ steps.set-matrix.outputs.schemas }}
      index: ${{ steps.set-matrix.outputs.index }}
      contexts: ${{ steps.set-matrix.outputs.contexts }}

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v2
  
  
  buildIndexPath:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: ${{ fromJson(needs.generateInputPaths.outputs.index) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Print Index
      run: touch ${{ matrix.index }}.html
    - name: action-ejs
      uses: jaywcjlove/action-ejs@v1.0.2
      with:
        template: |
          <main class="page-content" aria-label="Content">
            <%= markdown %>
          </main>
        # output html path
        vars-file: |
          {"markdown": "${{ matrix.index }}" }
        output: ${{ matrix.index }}.html
        
  buildSchemasPath:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schemas: ${{ fromJson(needs.generateInputPaths.outputs.schemas) }}
    steps:
    - name: Print Schema
      run: echo "running path ${{ matrix.schemas }}"
      
  buildContextsPath:
    needs: generateInputPaths
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contexts: ${{ fromJson(needs.generateInputPaths.outputs.contexts) }}
    steps:
    - name: Print Contexts
      run: echo "running path ${{ matrix.contexts }}"


#     - name: action-ejs
#       uses: jaywcjlove/action-ejs@v1.0.2
#       with:
#         template: |
#           <%= markdown %>
#         # output html path
#         vars-file: |
#           {"markdown": "./about.md" }
#         output: ./_site/index.html
#     - name: Upload artifact
#       uses: actions/upload-pages-artifact@v1
#       with:
#         path: ./_site/
# # Deployment job
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v1
