# Sample workflow for building and deploying a Action-EJS site to GitHub Pages
name: Deploy action-ejs with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v2
#     - name: Converts Markdown to HTML
#       uses: jaywcjlove/markdown-to-html-cli@main
#       with:
#         output: build/index.html
    - run: mkdir ./_site
    - name: action-ejs
      # You may pin to the exact commit or the version.
      # uses: jaywcjlove/action-ejs@9744c37783fdb75ced4d793ebc1e7dfce0876a0d
      uses: jaywcjlove/action-ejs@v1.0.2
      with:
        template: |
          <h1> commiter: <%= markdown %></h1>
        # output html path
        vars-file: |
          {"markdown": "./about.md" }
        output: ./_site/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_site/index.html
# Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
