- name: action-ejs
  # You may pin to the exact commit or the version.
  # uses: jaywcjlove/action-ejs@9744c37783fdb75ced4d793ebc1e7dfce0876a0d
  uses: jaywcjlove/action-ejs@v1.0.2
  with:
    # Your GITHUB_TOKEN
    ## token: # optional, default is ${{ github.token }}
    # Input ESJ template string
    template: <div><%= LICENSE %></div><div><%= markdown %></div>
    # Input ESJ template file path.
    ## template-file: # optional
    # Read the contents of the file into a vars.
    ## vars-file: # optional, default is {}
    # Input variables. A dictionary of variables in JSON format to be used in the template. 
    ## vars: # optional, default is {}
    # A JSON format string of options to be passed to the template engine.
    ## options: # optional, default is {}
    # output html path
    output: ./_site
